name: Playwright Allure-Report
on:
  push:
    branches: additional
jobs:    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Install Playwright and Browsers
      run: npx playwright install
    - run: npm test     

    - name: Get Allure History
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history


        steps:
          - name: Checkout code
            uses: actions/checkout@v2
      
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: 18
      
          - name: Install Java
            run: |
              sudo apt-get update
              sudo apt-get install openjdk-8-jre
              echo "JAVA_HOME=$(which java)" >> $GITHUB_ENV
      
          - name: Install dependencies
            run: npm ci
      
          - name: Install Playwright Browsers
            run: npx playwright install --with-deps
      
          - name: Run Playwright tests
            run: npm run test --ignore-https-errors
      
          - name: Generate Allure report
            run: npm run generate-allure-report